"$schema" = 'https://starship.rs/config-schema.json'

format = """
[î‚¶](mauve)\
$os\
$username\
[î‚°](bg:blue fg:mauve)\
$directory\
[î‚°](fg:blue bg:teal)\
$git_branch\
$git_status\
[î‚°](fg:teal bg:red)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\  
$kotlin\
$haskell\
$python\
$dart\
$dotnet\
$deno\
$cmake\
$gleam\
$erlang\
$elixir\
$gradle\
$zig\
$nix_shell\
[î‚°](fg:red bg:surface2)\
$docker_context\
$conda\
[î‚°](fg:surface2 bg:surface0)\
$time\
[î‚´ ](fg:surface0)\
$line_break$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:mauve fg:text"

[username]
show_always = true
style_user = "bg:mauve fg:text"
style_root = "bg:mauve fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:text bg:blue"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ï˜"
style = "bg:teal"
format = '[[ $symbol $branch ](fg:text bg:teal)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:text bg:teal)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[c]
symbol = "î˜"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[rust]
symbol = "î¨"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[golang]
symbol = "î˜§"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[java]
symbol = "î‰–"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[kotlin]
symbol = "î˜´"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[haskell]
symbol = "î˜Ÿ"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[python]
symbol = "î˜†"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[dart]
symbol = "î˜"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[dotnet]
symbol = "î¿"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[deno]
symbol = "ğŸ¦•"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[cmake]
symbol = "ïƒƒ"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[gleam]
symbol = "î‰µ"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[erlang]
symbol = "î±"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[elixir]
symbol = "î‰µ"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[gradle]
symbol = "î™ "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[zig]
symbol = "îš©"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[nix_shell]
symbol = "ïŒ“"
style = "bg:red"
format = '[[ $symbol( $version) ](fg:text bg:red)]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:surface2"
format = '[[ $symbol( $context) ](fg:text bg:surface2)]($style)'

[conda]
style = "bg:surface2"
format = '[[ $symbol( $environment) ](fg:text bg:surface2)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:surface0"
format = '[[ ïº $time ](fg:text bg:surface0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ï²](bold fg:green)'
error_symbol = '[ï²](bold fg:red)'
vimcmd_symbol = '[ï´](bold fg:green)'
vimcmd_replace_one_symbol = '[ï´](bold fg:mauve)'
vimcmd_replace_symbol = '[ï´](bold fg:mauve)'
vimcmd_visual_symbol = '[ï´](bold fg:blue)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
