"$schema" = 'https://starship.rs/config-schema.json'

palette = "rose_pine"

format = """
[î‚¶](love)\
$os\
$username\
[î‚°](bg:gold fg:love)\
$directory\
[î‚°](bg:pine fg:gold)\
$git_branch\
$git_status\
[î‚°](fg:pine bg:iris)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\  
$kotlin\
$haskell\
$python\
$dart\
$dotnet\
$deno\
$cmake\
$gleam\
$erlang\
$elixir\
$gradle\
$zig\
$nix_shell\
[î‚°](fg:iris bg:foam)\
$docker_context\
$conda\
[î‚°](fg:foam bg:rose)\
$time\
[î‚´ ](fg:rose)\
$line_break$character"""

[os]
disabled = false
style = "bg:love fg:overlay"

[os.symbols]
Windows = "îœ"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[username]
show_always = true
style_user = "bg:love fg:overlay"
style_root = "bg:love fg:overlay"
format = '[ $user ]($style)'

[directory]
style = "fg:base bg:gold"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:pine"
format = '[[ $symbol $branch ](fg:base bg:pine)]($style)'

[git_status]
disabled = false
style = "bg:pine fg:base"
format = '[[($all_status$ahead_behind )](fg:base bg:pine)]($style)'
up_to_date = '[ âœ“](bg:pine fg:base)'
untracked = '[?($count)](bg:pine fg:base)'
stashed = '[$](bg:pine fg:base)'
modified = '[!($count)](bg:pine fg:base)'
renamed = '[Â»($count)](bg:pine fg:base)'
deleted = '[âœ˜($count)](bg:pine fg:base)'
staged = '[++($count)](bg:pine fg:base)'
ahead = '[â‡¡($count)](bg:pine fg:base)'
diverged = 'â‡•[(bg:pine fg:base)[â‡¡($ahead_count)](bg:pine fg:base)[â‡£($behind_count)](bg:pine fg:base)](bg:pine fg:base)'
behind = '[â‡£($count)](bg:pine fg:base)'

[nodejs]
symbol = "îœ˜"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[c]
symbol = "î˜"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[rust]
symbol = "î¨"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[golang]
symbol = "î˜§"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[java]
symbol = "î‰–"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[kotlin]
symbol = "î˜´"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[haskell]
symbol = "î˜Ÿ"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[python]
symbol = "î˜†"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[dart]
symbol = "î˜"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[dotnet]
symbol = "î¿"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[deno]
symbol = "ğŸ¦•"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[cmake]
symbol = "ïƒƒ"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[gleam]
symbol = "î‰µ"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[erlang]
symbol = "î±"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[elixir]
symbol = "î‰µ"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[gradle]
symbol = "î™ "
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[zig]
symbol = "îš©"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[nix_shell]
symbol = "ïŒ“"
style = "bg:iris"
format = '[[ $symbol( $version) ](fg:base bg:iris)]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:foam"
format = '[[ $symbol( $context) ](fg:base bg:foam)]($style)'

[conda]
symbol = "ï„Œ "
style = "bg:foam"
format = '[[ $symbol( $environment) ](fg:base bg:foam)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:rose"
format = '[[ ïº $time ](fg:base bg:rose)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[[âœ](bold fg:green) â¯](gold)'
error_symbol = '[[âœ](bold fg:red) â¯](gold)'
vimcmd_symbol = '[ï´](bold fg:green)'
vimcmd_replace_one_symbol = '[ï´](bold fg:red)'
vimcmd_replace_symbol = '[ï´](bold fg:red)'
vimcmd_visual_symbol = '[ï´](bold fg:gold)'

[palettes.rose_pine]
base = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
gold = "#f6c177"
rose = "#ebbcba"
pine = "#31748f"
foam = "#9ccfd8"
iris = "#c4a7e7"
highlight_low = "#21202e"
highlight_med = "#403d52"
highlight_high = "#524f67"